# please set your database name (and settings)

test:
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  adapter: postgresql
  encoding: unicode
  database: sinatras-skeleton
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>
  pool: 5

development:
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  adapter: postgresql
  encoding: unicode
  database: sinatras-skeleton
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>
  pool: 5

production:
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  adapter: postgresql
  encoding: unicode
  database: sinatras-skeleton
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>
  pool: 5
